//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson11.LinqEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_PHUONG_XA
    {
        public int ID { get; set; }
        public string MA { get; set; }
        public string NAME { get; set; }
        public string MO_TA { get; set; }
        public Nullable<int> ID_QUAN_HUYEN { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public string NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_CAP_NHAT { get; set; }
        public string NGUOI_CAP_NHAT { get; set; }
        public Nullable<int> TRANG_THAI { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
    }
}
