//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson11.LinqEntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DEVHRMEntities : DbContext
    {
        public DEVHRMEntities()
            : base("name=DEVHRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DM_PHUONG_XA> DM_PHUONG_XA { get; set; }
        public virtual DbSet<DM_QUAN_HUYEN> DM_QUAN_HUYEN { get; set; }
        public virtual DbSet<DM_TINH_THANH> DM_TINH_THANH { get; set; }
    }
}
